# Generated by Django 3.1.2 on 2022-02-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fruit_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
